#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const root = path.resolve(__dirname, "..");
const srcDir = path.join(root, "assets/css/src");
const outFile = path.join(root, "assets/css/main.css");
const tmpStyl = path.join(root, "assets/css/.build-entry.styl");
const tmpOut = path.join(root, "assets/css/.build-stylus.css");

function walk(dir, pred, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(p, pred, acc);
    else if (pred(p)) acc.push(p);
  }
  return acc;
}

function buildEntry() {
  // Upstream index.styl uses hexo-config(); replace with unconditional imports
  // for a theme-consumer build (all surfaces compiled; toggles are CSS presence ok).
  const entry = `
// Auto-generated by tools/build-css.js — do not edit
@import '_third-party/normalize.min.css'
@import 'var'
@import '_global/*'
@import '_highlight/highlight'
@import '_page/*'
@import '_layout/*'
@import '_tags/*'
@import '_mode/*'
@import '_third-party/*'
@import '_search/index'
@import '_search/local-search'
@import '_search/algolia'
`;
  fs.writeFileSync(tmpStyl, entry);
}

function compileStylus() {
  buildEntry();
  const r = spawnSync(
    "stylus",
    [tmpStyl, "-o", path.dirname(tmpOut), "--include", srcDir, "--include-css"],
    { cwd: srcDir, encoding: "utf8" }
  );
  // stylus -o dir writes basename.css next to entry path resolution
  const produced = path.join(path.dirname(tmpStyl), ".build-entry.css");
  if (r.status !== 0) {
    console.error(r.stdout || "");
    console.error(r.stderr || "");
    // Fallback: keep existing main.css extra-only path
    throw new Error("stylus compile failed: " + (r.stderr || r.stdout || r.status));
  }
  if (fs.existsSync(produced)) {
    fs.renameSync(produced, tmpOut);
  } else if (fs.existsSync(tmpOut)) {
    // ok
  } else {
    // stylus may write to cwd
    const alt = path.join(srcDir, ".build-entry.css");
    if (fs.existsSync(alt)) fs.renameSync(alt, tmpOut);
    else throw new Error("stylus produced no css output");
  }
}

function concatExtra(baseCss) {
  const extraDir = path.join(srcDir, "_extra");
  const files = walk(extraDir, (p) => p.endsWith(".css") && fs.statSync(p).size > 0).sort();
  // prioritize home_top visuals
  const priority = [
    "home_top/home_top.css",
    "home_top/categorygroup.css",
    "home_top/top_group_banner.css",
    "home_top/home_top_post_group.css",
    "home_top/swiperstyle.css",
    "essay_page/home_essay_bar.css",
    "essay_page/essay_page.css",
    "categoryBar/categoryBar.css",
    "catalog_list/catalog_list.css",
    "console/console.css",
    "skills/skills.css",
  ];
  const ordered = [];
  for (const rel of priority) {
    const abs = path.join(extraDir, rel);
    if (files.includes(abs)) ordered.push(abs);
  }
  for (const f of files) if (!ordered.includes(f)) ordered.push(f);

  let out = baseCss.replace(/@import[^;]*_extra[^;]*;/g, '');
  out = out.trim() + "\n\n/* ===== inlined _extra CSS via tools/build-css.js ===== */\n";
  for (const f of ordered) {
    const rel = path.relative(extraDir, f);
    out += `\n/* --- _extra/${rel} --- */\n`;
    out += fs.readFileSync(f, "utf8").trim() + "\n";
  }
  return out;
}

function main() {
  let stylusCss = "";
  try {
    compileStylus();
    stylusCss = fs.readFileSync(tmpOut, "utf8");
    console.log("stylus ok:", Buffer.byteLength(stylusCss), "bytes");
  } catch (e) {
    console.warn("stylus failed, using previous main.css as base:", e.message);
    stylusCss = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : "";
    // strip previously inlined extra to avoid duplication
    const idx = stylusCss.indexOf("/* ===== inlined");
    if (idx !== -1) stylusCss = stylusCss.slice(0, idx);
  }

  const finalCss = concatExtra(stylusCss);
  fs.writeFileSync(outFile, finalCss);
  console.log("wrote", outFile, Buffer.byteLength(finalCss), "bytes");

  // cleanup temps
  for (const p of [tmpStyl, tmpOut, path.join(path.dirname(tmpStyl), ".build-entry.css")]) {
    try { fs.unlinkSync(p); } catch (_) {}
  }
}

main();